package domb.rules;

import java.util.Set;

import function domb.rules.DroolsUtils.debugLhsValue;
import domb.app.model.vehicle.Failure;
import domb.app.model.enums.PartEnum;

import domb.app.model.events.PartWarningEvent;

rule "ENGINE WARNING"
  no-loop true
  when
    $newFailure: Failure(part == PartEnum.MAJOR_DRIVE_BELT || part == PartEnum.MAJOR_ENGINE_LUBRICATION) and
    
    $previouesBeltFailures: Set() from accumulate(
        $previouesFailure: Failure(
            this != $newFailure,
            part == PartEnum.MAJOR_DRIVE_BELT,
            vehicleManufacturer == $newFailure.vehicleManufacturer,
            vehicleModel == $newFailure.vehicleModel,
            this before[1s, 30d] $newFailure 
        ), collectSet($previouesFailure)
    ) and
    
    $previouesLubractionFailures: Set() from accumulate(
        $previouesLubricationFailure: Failure(
            this != $newFailure,
            part == PartEnum.MAJOR_ENGINE_LUBRICATION,
            vehicleManufacturer == $newFailure.vehicleManufacturer,
            vehicleModel == $newFailure.vehicleModel,
            this before[1s, 30d] $newFailure 
        ), collectSet($previouesLubricationFailure)
    ) and

    eval($previouesBeltFailures.size() > 0 && $previouesLubractionFailures.size() > 0)
  then
    System.out.println("RULE EXECUTED: DETECTED ENGINE WARNING");
    insert(new PartWarningEvent(PartEnum.ENGINE_WARNING));

end