package domb.app.model.enums;

public enum PartEnum {
    NONE, UNKNOWN, 
    
    // ODB
    PCV, RESET_OBD, SPARK_PLUGS, FUEL_TANK, VAPOR_SENSOR,
    CATALYZER, FUEL_PUMP, PCV_LEAK, MAF, RADIATOR_CAP, NONE_EXHAUST,
    DRAIN_PAN_AC, FUEL_INJECTION_SENSOR, AIR_FILTER,
    
    //USER INPUT
    ENGINE_LUBRICATION, ADD_OIL, LOOSE_VALVE, DRIVE_BELT, BREAK_PADS,

    //MAJOR
    MAJOR_ENGINE_LUBRICATION, MAJOR_DRIVE_BELT, MAJOR_SPARK_PLUGS,

    //WARNING
    ENGINE_WARNING,

    //ESSENTIAL
    ESSENTIAL_FIX_ENGINE
}
